### ISSUE TITLE
Wrong Number of Arguments for Show Plan Breakout

### ISSUE THREAD

**Issue by FsDevNinja** [rewindit/baremetrics#3]
Using version 1.0.0, I run this code after initializing client:
`client.show_plan_breakout(metric: "mrr", start_date: "2017-8-14", end_date: "2017-11-11")`

I get the following error: 

`ArgumentError: wrong number of arguments (given 4, expected 3)
from /Users/devninja/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/baremetrics_api-1.0.0/lib/baremetrics_api/endpoint/metrics.rb:74:in `show_plan_breakout_request'`

Am I missing something here?

Thanks @smandegar

**Comment by scottrobertson** [comment]
Looks like `show_plan_breakout` is passing `page` to `show_plan_breakout_request` but `show_plan_breakout_request` is not expecting `page`.

**Comment by smandegar** [comment]
@scottrobertson is right. This issue should be fixed now with version `1.0.1`
